name: Deploy to Cafe24 (SFTP)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: field0327.cafe24.com   # 카페24 FTP 서버 주소
          port: 22
          username: your_ftp_id        # 카페24 FTP ID
          password: ${{ secrets.SFTP_PASSWORD }}
          sftp_only: true
          local_path: "www/*"
          remote_path: "/field0327/www/"
          delete_remote_files: false
